pie showData
    title My Pie Chart
    "Homework" : 30
    "Sleep" : 25
    "Study" : 45
    
    %%{init: {
      'pie': {
        'textPosition': 0.5,
        'useWidth': 18
      },
      'themeVariables': {
        'pie1': '#FF5733',
        'pie2': '#33FF57',
        'pie3': '#3357FF'
      }
    }}%%